// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StockFlow.Infrastructure.Database;

#nullable disable

namespace StockFlow.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251219033642_RemoveInventoryModel")]
    partial class RemoveInventoryModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<Guid>("UsersId")
                        .HasColumnType("uuid")
                        .HasColumnName("users_id");

                    b.HasKey("RoleId", "UsersId")
                        .HasName("pk_role_user");

                    b.HasIndex("UsersId")
                        .HasDatabaseName("ix_role_user_users_id");

                    b.ToTable("role_user", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_categories_name");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("integer")
                        .HasColumnName("order_status");

                    b.Property<DateTime?>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_orders_supplier_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_orders_warehouse_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.OrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_price");

                    b.HasKey("Id")
                        .HasName("pk_order_items");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_items_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_order_items_product_id");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            Name = "InventoryView"
                        },
                        new
                        {
                            Id = 1001,
                            Name = "InventoryCreate"
                        },
                        new
                        {
                            Id = 1002,
                            Name = "InventoryUpdate"
                        },
                        new
                        {
                            Id = 1003,
                            Name = "InventoryDelete"
                        },
                        new
                        {
                            Id = 1004,
                            Name = "InventoryAdjustStock"
                        },
                        new
                        {
                            Id = 1005,
                            Name = "InventoryReserveStock"
                        },
                        new
                        {
                            Id = 1006,
                            Name = "InventoryReleaseStock"
                        },
                        new
                        {
                            Id = 1007,
                            Name = "InventoryTransferStock"
                        },
                        new
                        {
                            Id = 1008,
                            Name = "InventoryViewCost"
                        },
                        new
                        {
                            Id = 1009,
                            Name = "InventoryUpdateCost"
                        },
                        new
                        {
                            Id = 1010,
                            Name = "InventoryViewValuation"
                        },
                        new
                        {
                            Id = 1200,
                            Name = "InventoryCreateAdjustment"
                        },
                        new
                        {
                            Id = 1201,
                            Name = "InventoryViewAdjustment"
                        },
                        new
                        {
                            Id = 1202,
                            Name = "InventoryApproveAdjustment"
                        },
                        new
                        {
                            Id = 1203,
                            Name = "InventoryRejectAdjustment"
                        },
                        new
                        {
                            Id = 1300,
                            Name = "WarehouseView"
                        },
                        new
                        {
                            Id = 1301,
                            Name = "WarehouseCreate"
                        },
                        new
                        {
                            Id = 1302,
                            Name = "WarehouseUpdate"
                        },
                        new
                        {
                            Id = 1303,
                            Name = "WarehouseDelete"
                        },
                        new
                        {
                            Id = 1304,
                            Name = "WarehouseAssignUser"
                        },
                        new
                        {
                            Id = 1305,
                            Name = "WarehouseTransferInventory"
                        },
                        new
                        {
                            Id = 1400,
                            Name = "ProcurementViewSupplier"
                        },
                        new
                        {
                            Id = 1401,
                            Name = "ProcurementCreateSupplier"
                        },
                        new
                        {
                            Id = 1402,
                            Name = "ProcurementUpdateSupplier"
                        },
                        new
                        {
                            Id = 1403,
                            Name = "ProcurementCreatePurchaseOrder"
                        },
                        new
                        {
                            Id = 1404,
                            Name = "ProcurementUpdatePurchaseOrder"
                        },
                        new
                        {
                            Id = 1405,
                            Name = "ProcurementApprovePurchaseOrder"
                        },
                        new
                        {
                            Id = 1406,
                            Name = "ProcurementReceiveGoods"
                        },
                        new
                        {
                            Id = 1500,
                            Name = "ReportViewInventory"
                        },
                        new
                        {
                            Id = 1501,
                            Name = "ReportViewMovement"
                        },
                        new
                        {
                            Id = 1502,
                            Name = "ReportViewValuation"
                        },
                        new
                        {
                            Id = 1503,
                            Name = "ReportExport"
                        },
                        new
                        {
                            Id = 1504,
                            Name = "AuditViewLogs"
                        },
                        new
                        {
                            Id = 1505,
                            Name = "AuditExportLogs"
                        },
                        new
                        {
                            Id = 1600,
                            Name = "UserView"
                        },
                        new
                        {
                            Id = 1601,
                            Name = "UserCreate"
                        },
                        new
                        {
                            Id = 1602,
                            Name = "UserUpdate"
                        },
                        new
                        {
                            Id = 1603,
                            Name = "UserDeactivate"
                        },
                        new
                        {
                            Id = 1604,
                            Name = "RoleView"
                        },
                        new
                        {
                            Id = 1605,
                            Name = "RoleCreate"
                        },
                        new
                        {
                            Id = 1606,
                            Name = "RoleUpdate"
                        },
                        new
                        {
                            Id = 1607,
                            Name = "PermissionAssign"
                        },
                        new
                        {
                            Id = 1608,
                            Name = "PermissionRevoke"
                        },
                        new
                        {
                            Id = 1700,
                            Name = "IntegrationInventorySync"
                        },
                        new
                        {
                            Id = 1701,
                            Name = "IntegrationInventoryAdjust"
                        },
                        new
                        {
                            Id = 1702,
                            Name = "IntegrationInventoryExport"
                        },
                        new
                        {
                            Id = 1703,
                            Name = "IntegrationWebhookReceive"
                        },
                        new
                        {
                            Id = 1800,
                            Name = "SystemViewSettings"
                        },
                        new
                        {
                            Id = 1801,
                            Name = "SystemUpdateSettings"
                        });
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("sku");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_products_category_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "InventoryManager"
                        },
                        new
                        {
                            Id = 3,
                            Name = "WarehouseStaff"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Auditor"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Procurement"
                        },
                        new
                        {
                            Id = 6,
                            Name = "SystemIntegration "
                        });
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1001
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1002
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1003
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1004
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1005
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1006
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1007
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1008
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1009
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1010
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1200
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1201
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1202
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1203
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1300
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1301
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1302
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1303
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1304
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1305
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1400
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1401
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1402
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1403
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1404
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1405
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1406
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1500
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1501
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1502
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1503
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1504
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1505
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1600
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1601
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1602
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1603
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1604
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1605
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1606
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1607
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1608
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1700
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1701
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1702
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1703
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1800
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1801
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1001
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1002
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1003
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1004
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1007
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1008
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1009
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1010
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1200
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1201
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1202
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1203
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1500
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1501
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 1502
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1004
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1005
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1006
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1200
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1201
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1300
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1008
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1010
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1500
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1501
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1502
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1503
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1504
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 1505
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1400
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1401
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1402
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1403
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1404
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1405
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1406
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1700
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1701
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1702
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1000
                        },
                        new
                        {
                            RoleId = 6,
                            PermissionId = 1004
                        });
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("contact_info");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("QuantityChange")
                        .HasColumnType("integer")
                        .HasColumnName("quantity_change");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<Guid>("TransactionGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("transaction_group_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.Property<decimal?>("UnitCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("unit_cost");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid")
                        .HasColumnName("warehouse_id");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_transactions_order_id");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_transactions_product_id");

                    b.HasIndex("TransactionGroupId")
                        .HasDatabaseName("ix_transactions_transaction_group_id");

                    b.HasIndex("WarehouseId")
                        .HasDatabaseName("ix_transactions_warehouse_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("last_name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_warehouses");

                    b.ToTable("warehouses", (string)null);
                });

            modelBuilder.Entity("RoleUser", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_roles_role_id");

                    b.HasOne("StockFlow.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_user_users_users_id");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Order", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Supplier", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_suppliers_supplier_id");

                    b.HasOne("StockFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_orders_warehouses_warehouse_id");

                    b.Navigation("Supplier");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.OrderItem", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Order", null)
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_order_items_orders_order_id");

                    b.HasOne("StockFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Product", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_products_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("StockFlow.Domain.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("StockFlow.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .HasConstraintName("fk_transactions_orders_order_id");

                    b.HasOne("StockFlow.Domain.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_products_product_id");

                    b.HasOne("StockFlow.Domain.Entities.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transactions_warehouses_warehouse_id");

                    b.Navigation("Order");

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("StockFlow.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
